DotNetShop/DotNetShop/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotNetShop.DAL.Model;
using DotNetShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace DotNetShop.Controllers
{
    public class StoreController : Controller
    {
        private IMemoryCache _cache;
        private readonly MicomDBContext dbContext = new MicomDBContext();

        public StoreController(IMemoryCache cache)
        {
            _cache = cache;
        }

        public IActionResult List(int categoryId)
        {
            var listCategoryId = dbContext.Categories.FirstOrDefault(b => b.Id == categoryId).Id;
            var popProd = dbContext.Products.Where(c => c.CategoryId == listCategoryId && c.IsHidden == false).OrderBy(g => Guid.NewGuid()).Take(3).ToList();
            var prod = dbContext.Products.Include(x => x.ProductsGalleries).Include(x => x.ProductsSpecValues).ThenInclude(x => x.Specification).Where(c => c.CategoryId == listCategoryId).ToList();
            var listVM = new StoreViewModel()
            {
                Products = prod,
                PopularProducts = popProd
            };

            return View(listVM);
        }
        public IActionResult Details(string id)
        {
            var productDetail = dbContext.Products.Include(x => x.ProductsGalleries)
                .Include(x => x.ProductsSpecValues)
                .ThenInclude(x => x.Specification)
                .Include(x => x.Manufacturer)
                .Include(x => x.Warehouse)
                .Where(p => p.Id == int.Parse(id))
                .FirstOrDefault();
            bool isAdmin = User.IsInRole("Admin");
            ViewBag.UserIsAdmin = isAdmin;

            return View(productDetail);
        }

        public IActionResult AllCategories(int mainCategoryId)
        {
            var actualMainCategoryId = dbContext.Categories.FirstOrDefault(b => b.Id == mainCategoryId).Id;
            var actualMainSubCategoryId = dbContext.Categories.Where(sc => sc.ParentCategoryId == actualMainCategoryId).FirstOrDefault().Id;
            var actualMainCategory = dbContext.Categories.Where(x => x.Id == actualMainCategoryId).ToList();
            var actualMainSubCategory = dbContext.Categories.Where(c => c.ParentCategoryId == actualMainCategoryId).ToList();
            var actualMainSubSubCategory = dbContext.Categories.Where(d => d.ParentCategoryId == actualMainSubCategoryId).ToList();
            var countProductOnSubCategory = dbContext.Categories.Include(prods => prods.Products).Count();
            var countSubCategories = dbContext.Categories.Where(d => d.ParentCategoryId == actualMainSubCategoryId).Count();
            var cate = new CategoriesViewModel()
            {
                ActualCategory = actualMainCategory,
                ActualParentCategory = actualMainSubCategory,
                ActualParentSubCategory = actualMainSubSubCategory,
                CountProductOnSubCategory = countProductOnSubCategory,
                CountSubCategories = countSubCategories
            };
            return View(cate);
        }
        public IActionResult ProductsSuggestions(string term)
        {
            var products = this.dbContext.Products
                .Where(p => p.Name.ToLower()
                .Contains(term.ToLower()))
                .Take(5)
                .Select(p => new
                {
                    label = p.Name,
                    photo = p.ProductsGalleries.Select(photoUrl => photoUrl.PhotoUrl).Take(1)
                });
            return new JsonResult(products);
        }
        public IActionResult SearchResult()
        {
            var queryTerm = (string)default;
            if (!(Request.HasFormContentType && Request.Form != null && Request.Form.Count() > 0)) return RedirectToAction("Cart", "Cart");
            else
            {
                queryTerm = Request.Form["topSearchInputQuery"].ToString();
            }
            if (dbContext.Products.Any(cp => cp.Name == queryTerm)) return RedirectToAction("Details", new { id = dbContext.Products.FirstOrDefault(cp => cp.Name == queryTerm).Id });

            var qProducts = dbContext.Products.Include(ph => ph.ProductsGalleries).Include(x => x.ProductsSpecValues).ThenInclude(x => x.Specification).Where(p => p.Name.ToLower().Contains(queryTerm.ToLower())).ToList();


            var queryProducts = new StoreViewModel()
            {
                Products = qProducts,
                QueryTerm = queryTerm
            };


            return View(queryProducts);
        }
    }
}

DotNetShop/DotNetShop/ViewComponents/NavViewComponent.cs
using DotNetShop.DAL.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetShop.ViewComponents
{
    public class NavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            MicomDBContext _dbContext = new MicomDBContext();
            var cat = await _dbContext.Categories.ToListAsync();
            return View(cat);
        }
    }
}

DotNetShop/DotNetShop/ViewComponents/UserPanelViewComponent.cs
using DotNetShop.DAL.Model;
using DotNetShop.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetShop.ViewComponents
{
    public class UserPanelViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
                return View();
        }
    }
}

DotNetShop/DotNetShop/Views/Shared/_AdminPanelMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="userPanelOptionsBox">
    <div class="userPanelSmallContainer">
        <div class="panelBox">
            <p class="userPanelUserOptionsText"><span class="material-icons">admin_panel_settings</span> Panel administratora</p>
            <span class="material-icons ddArrowIcon">arrow_drop_down</span>
        </div>
        <div class="panelTabs">
            <a href="@Url.Action("UserOrders","Manage")" class="userPanelUserOptions lineBorderTop"><span class="material-icons iconMargin">assignment</span> Zamówienia</a>
            <a href="@Url.Action("AddProductSpecification","Manage")" class="userPanelUserOptions"><span class="material-icons iconMargin">receipt_long</span> Specyfikacje</a>
            <a href="@Url.Action("AddCategory","Manage")" class="userPanelUserOptions"><span class="material-icons iconMargin">category</span> Kategorie</a>
            <a href="@Url.Action("AddManufacturer","Manage")" class="userPanelUserOptions"><span class="material-icons iconMargin">precision_manufacturing</span> Producenci</a>
            <a href="@Url.Action("AddProduct","Manage")" class="userPanelUserOptions"><span class="material-icons iconMargin">local_offer</span> Produkty</a>
        </div>
    </div>
</div>

<script>
    $(".ddArrowIcon").click(function () {
            if ($(".panelTabs").css("display") == 'none') {
                $(".panelTabs").css("display", "flex");
            } else {
                $(".panelTabs").css("display", "none");
            }
        });
</script>

DotNetShop/DotNetShop/Views/Shared/_MainLayout.cshtml
@{

}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet">
    <bundle name="wwwroot/bundles/site.min.css" />
</head>
<body>
    <header class="header-container">
        <div class="header-box">
            <img class="site-logo" src="@Url.Content("~/img/logo2.png")" onclick="window.location='@Url.Action("Index", "Home")'" style="cursor: pointer;" />
        </div>
        <div class="header-box">
            <div class="search-box">
                <form id="topSearchBarForm" method="post" action="@Url.Action("SearchResult","Store")">
                    <input type="search" id="topSearchBarInput" name="topSearchInputQuery" data-query-source="@Url.Action("ProductsSuggestions", "Store")" placeholder="Wyszukaj.." />
                    <button type="submit" class="topSearchBarBttn">
                        <span class="material-icons iconSearch">search</span>
                    </button>
                </form>
                <ul class="list-group" id="result"></ul>
            </div>

        </div>
        <div class="header-box mainNav">
            <div class="user-panel-box">
                @await Component.InvokeAsync("CartCounter")
            </div>
            <div class="user-panel-box">
                @await Component.InvokeAsync("UserPanel")
            </div>
        </div>
        <div class="header-box mobNav">
            <div class="user-panel-box">
                <span class="material-icons iconMob mobSearch">search</span>
            </div>
            <div class="user-panel-box">
                @await Component.InvokeAsync("MobilePanel")
            </div>
            <div class="user-panel-box">
                <span class="material-icons iconMob catMobMenu">menu</span>
            </div>
        </div>

    </header>
    @await Component.InvokeAsync("QuickBasket")
    <nav class="nav-container">
        @await Component.InvokeAsync("Nav")
    </nav>
    <main class="main-container stickyMenuMainContainerPush">
        @RenderBody()
    </main>
    <footer class="mainFooter">
        <div class="footerContainer">
            <div class="footerSmallContainer">
                <h3 class="footerH3">Informacje kontaktowe</h3>
                <div class="footerTile">
                    <p class="footerMainText">Adres:</p>
                    <p class="footerText">ul. Kombatantów 1A, Wrocław, Polska</p>
                    <p class="footerMainText">Email:</p>
                    <p class="footerText">kontakt@micom.pl</p>
                </div>
            </div>
            <div class="footerSmallContainer">
                <div class="footerTile">
                    <p class="footerMainText">Telefon:</p>
                    <p class="footerText">+48 123 456 789</p>
                    <p class="footerMainText">Godziny otwarcia:</p>
                    <p class="footerText">Pn - Sb / 09:00 - 21:00</p>
                </div>
            </div>
            <div class="footerSmallContainer">
                <h3 class="footerH3">Twoje konto</h3>
                <div class="footerTile">
                    <a href="#">O nas</a>
                    <a href="#">Kontakt</a>
                    <a href="@Url.Action("UserSettings","Manage")">Twoje konto</a>
                </div>
                <div class="footerTile">
                    <a href="@Url.Action("UserOrders","Manage")">Historia zamówień</a>
                </div>
            </div>
        </div>
        <div class="footerBottom">
            <p class="copyrightText">©Copyright 2021 by miCOM. Wszelkie prawa zastrzeżone</p>
            <div class="socialMediaContainer">
                <img src="~/img/facebook.svg" alt="facebook" class="imgSocialMedia" />
                <img src="~/img/youtube.svg" alt="youtube" class="imgSocialMedia" />
                <img src="~/img/twitter.svg" alt="twitter" class="imgSocialMedia" />
            </div>
        </div>
    </footer>
    <bundle name="wwwroot/bundles/site.min.js" />
    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

DotNetShop/DotNetShop/Views/Shared/_UserPanelMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <div class="userPanelOptionsBox">
        <div class="userPanelSmallContainer">
            <a href="@Url.Action("UserSettings","Manage")" class="userPanelUserOptions"><span class="material-icons iconMargin">settings</span> Ustawienia konta</a>
            <a href="@Url.Action("UserOrders","Manage")" class="userPanelUserOptions activeUserPanel"><span class="material-icons iconMargin">assignment</span> Zamówienia</a>
        </div>
    </div>

DotNetShop/DotNetShop/Views/Shared/_slideMessage.cshtml
@if (TempData["slideMsg"] != null)
{
    <div class="slideMessage">
        <p class="slideText">@TempData["slideMsg"]</p>
        <div class="slideMessageCloseBttn">
            <span class="material-icons">close</span>
        </div>
    </div>
}